---
- name: Set up development environment
  hosts: local
  gather_facts: true

  roles:
    - role: common
      tags: [common]
    - role: cli
      tags: [cli]
    - role: shell
      tags: [shell]
    - role: languages
      tags: [languages]
    - role: docker
      tags: [docker]
    - role: dotfiles
      tags: [dotfiles]
